### ISSUE TITLE
Missing Driver API for uncited items/bibliography generation

### ISSUE THREAD

**Issue by adomasven** [zotero/citeproc-rs#22]
This can currently be done by adding all the uncited items into a cluster with an inText position of 99999 or something, but there should certainly be a proper API method to add uncited items that should appear in the bibliography.

**Comment by cormacrelf** [comment]
Indeed. They can already be represented internally, so this will be easy.

**Comment by cormacrelf** [comment]
Closed in #67, took a bit more work than that, what with the 'ghost entries'. See https://github.com/cormacrelf/citeproc-rs/blob/master/crates/wasm/README.md#uncited-items

**Comment by cormacrelf** [comment]
Actually, leaving open until I document the two bibliography APIs
